# Generated by Django 2.1.5 on 2019-05-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='_id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmrd',
            field=models.BooleanField(default=False),
        ),
    ]
