# Generated by Django 2.1.5 on 2019-05-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190523_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='increase',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
